class StateInfo {
  final String stateName;
  final String stateDbName;
  final int deputyCount;

  final int areaCount;

  StateInfo(
    this.stateName,
    this.stateDbName,
    this.deputyCount,
    this.areaCount,
  );
}

class TurkeyCities {
  List<StateInfo> cities = [
    StateInfo("", "", 0, 0),
    StateInfo("Adana", "ADANA", 15, 1),
    StateInfo("Adıyaman", "ADIYAMAN", 5, 1),
    StateInfo("Afyonkarahisar", "AFYON", 6, 1),
    StateInfo("Ağrı", "AGRI", 4, 1),
    StateInfo("Amasya", "AMASYA", 3, 1),
    StateInfo("Ankara", "ANKARA1", 36, 3),
    StateInfo("Antalya", "ANTALYA", 17, 1),
    StateInfo("Artvin", "ARTVIN", 2, 1),
    StateInfo("Aydın", "AYDIN", 8, 1),
    StateInfo("Balıkesir", "BALIKESIR", 9, 1),
    StateInfo("Bilecik", "BILECIK", 2, 1),
    StateInfo("Bingöl", "BINGOL", 3, 1),
    StateInfo("Bitlis", "BITLIS", 3, 1),
    StateInfo("Bolu", "BOLU", 3, 1),
    StateInfo("Burdur", "BURDUR", 3, 1),
    StateInfo("Bursa", "BURSA1", 20, 2),
    StateInfo("Çanakkale", "CANAKKALE", 4, 1),
    StateInfo("Çankırı", "CANKIRI", 2, 1),
    StateInfo("Çorum", "CORUM", 4, 1),
    StateInfo("Denizli", "DENIZLI", 7, 1),
    StateInfo("Diyarbakır", "DIYARBAKIR", 12, 1),
    StateInfo("Edirne", "EDIRNE", 4, 1),
    StateInfo("Elazığ", "ELAZIG", 5, 1),
    StateInfo("Erzincan", "ERZINCAN", 2, 1),
    StateInfo("Erzurum", "ERZURUM", 6, 1),
    StateInfo("Eskişehir", "ESKISEHIR", 6, 1),
    StateInfo("Gaziantep", "GAZIANTEP", 14, 1),
    StateInfo("Giresun", "GIRESUN", 4, 1),
    StateInfo("Gümüşhane", "GUMUSHANE", 2, 1),
    StateInfo("Hakkari", "HAKKARI", 3, 1),
    StateInfo("Hatay", "HATAY", 11, 1),
    StateInfo("Isparta", "ISPARTA", 4, 1),
    StateInfo("Mersin", "MERSIN", 13, 1),
    StateInfo("İstanbul", "ISTANBUL1", 98, 3),
    StateInfo("İzmir", "IZMIR1", 28, 2),
    StateInfo("Kars", "KARS", 3, 1),
    StateInfo("Kastamonu", "KASTAMONU", 3, 1),
    StateInfo("Kayseri", "KAYSERI", 10, 1),
    StateInfo("Kırklareli", "KIRKLARELI", 3, 1),
    StateInfo("Kırşehir", "KIRSEHIR", 2, 1),
    StateInfo("Kocaeli", "KOCAELI", 14, 1),
    StateInfo("Konya", "KONYA", 15, 1),
    StateInfo("Kütahya", "KUTAHYA", 5, 1),
    StateInfo("Malatya", "MALATYA", 6, 1),
    StateInfo("Manisa", "MANISA", 10, 1),
    StateInfo("Kahramanmaraş", "KAHRAMANMARAS", 8, 1),
    StateInfo("Mardin", "MARDIN", 6, 1),
    StateInfo("Muğla", "MUGLA", 7, 1),
    StateInfo("Muş", "MUS", 3, 1),
    StateInfo("Nevşehir", "NEVSEHIR", 3, 1),
    StateInfo("Niğde", "NIGDE", 3, 1),
    StateInfo("Ordu", "ORDU", 6, 1),
    StateInfo("Rize", "RIZE", 3, 1),
    StateInfo("Sakarya", "SAKARYA", 8, 1),
    StateInfo("Samsun", "SAMSUN", 9, 1),
    StateInfo("Siirt", "SIIRT", 3, 1),
    StateInfo("Sinop", "SINOP", 2, 1),
    StateInfo("Sivas", "SIVAS", 5, 1),
    StateInfo("Tekirdağ", "TEKIRDAG", 8, 1),
    StateInfo("Tokat", "TOKAT", 5, 1),
    StateInfo("Trabzon", "TRABZON", 6, 1),
    StateInfo("Tunceli", "TUNCELI", 1, 1),
    StateInfo("Şanlıurfa", "SANLIURFA", 14, 1),
    StateInfo("Uşak", "USAK", 3, 1),
    StateInfo("Van", "VAN", 8, 1),
    StateInfo("Yozgat", "YOZGAT", 4, 1),
    StateInfo("Zonguldak", "ZONGULDAK", 5, 1),
    StateInfo("Aksaray", "AKSARAY", 4, 1),
    StateInfo("Bayburt", "BAYBURT", 1, 1),
    StateInfo("Karaman", "KARAMAN", 3, 1),
    StateInfo("Kırıkkale", "KIRIKKALE", 3, 1),
    StateInfo("Batman", "BATMAN", 5, 1),
    StateInfo("Şırnak", "SIRNAK", 4, 1),
    StateInfo("Bartın", "BARTIN", 2, 1),
    StateInfo("Ardahan", "ARDAHAN", 2, 1),
    StateInfo("Iğdır", "IGDIR", 2, 1),
    StateInfo("Yalova", "YALOVA", 3, 1),
    StateInfo("Karabük", "KARABUK", 3, 1),
    StateInfo("Kilis", "KILIS", 2, 1),
    StateInfo("Osmaniye", "OSMANIYE", 4, 1),
    StateInfo("Düzce", "DUZCE", 3, 1),
  ];
}
